#Query to find a list of all the ships travelling between given two locations.

SELECT 
	TI.CRUISE_SHIP,
    C.CRUISE_NAME,
    CT.DEPART_PORT,
    CT.ARRIVAL_PORT,
    COUNT(*) AS TOTAL
FROM
	TRAVELLER_ITINERARY AS TI
INNER JOIN CRUISE_TRIP AS CT
	ON TI.CRUISE_TRIP_ID = CT.CRUISE_TRIP_ID
INNER JOIN CRUISE AS C
	ON TI.CRUISE_SHIP = C.CRUISE_NO
GROUP BY TI.CRUISE_SHIP;

